storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

server:
  http_listen_port: 3100

ingester:
  wal:
    enabled: true
    dir: /loki/wal

