global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['swarm-manager-1:8080', 'swarm-manager-2:8080', 'swarm-work:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['swarm-manager-1:9100', 'swarm-manager-2:9100', 'swarm-work:9100']

  - job_name: 'mongo-exporter'
    static_configs:
      - targets:
          - 'swarm-manager-1:9216'  # mongo1
          - 'swarm-manager-2:9217'  # mongo2
          - 'swarm-work:9218'       # mongo3

  - job_name: 'redis-exporter'
    static_configs:
      - targets:
          - 'swarm-manager-1:9121'
          - 'swarm-manager-2:9121'
          - 'swarm-work:9121'

  

