global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'mongo-exporter'
    static_configs:
      - targets: ['mongo-exporter:9216']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
  
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

