global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['docker-swarm-mgr-1:8080', 'docker-swarm-mgr-2:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['docker-swarm-mgr-1:9100', 'docker-swarm-mgr-2:9100']

  - job_name: 'mongo-exporter'
    static_configs:
      - targets: ['docker-swarm-mgr-1:9216']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['docker-swarm-mgr-2:9121']

